#+TITLE: FedBox: Turnkey Federated Social Networks

* Build Instructions
** Dependencies
   The dependencies required for building this project are:
   - None yet


   The dependencies for Buildroot are described in this [[https://buildroot.org/downloads/manual/manual.html#requirement][document]].

   If you are using Windows Subsystem for Linux, you must add the following to =/etc/wsl.conf=:
   #+begin_example
     [interop]
     appendWindowsPath=False
   #+end_example

** Preparing Sources
   First clone the Buildroot source and this repository:
   #+begin_src sh
     git clone https://github.com/buildroot/buildroot.git
     cd buildroot
     git checkout -b stable 2021.08.2

     cd ..
     git clone https://github.com/HOGGL/fedbox.git fedbox-external
   #+end_src
  
   Next find the defconfig for your single board computer in
   =buildroot/configs= and build the system image. The following
   example will build an image to be used by Qemu. This is useful for
   testing purposes. For details on running the image see
   =board/qemu/arm-vexpress/readme.txt= under the Buildroot tree.
   #+begin_src sh
     cd fedbox-external
     make -C ../buildroot BR2_EXTERNAL=$PWD O=$PWD/output \
	  qemu_arm_vexpress_defconfig
   #+end_src

** Image Creation
   Creating the filesystem image for the device is as follows:
   #+begin_src sh
     cd output
     make
   #+end_src

   It is a good idea to enable build caching if you will compile
   often. To enable this setting preform the following:
   #+begin_src sh
     make menuconfig # -> Build options -> Enable compiler cache
   #+end_src

   There will now be a complete filesystem image located under
   =output/images=. For example, when using the BeagleBone defconfig,
   a =sdcard.img= will be located in that folder and it can be flashed
   to a SD card using ~dd(1)~ and inserted into the device.
