#!/bin/sh

start() {
    printf "Starting pleroma: "
    su -s /bin/sh pleroma -c "~/bin/pleroma start"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping pleroma: "
    su -s /bin/sh pleroma -c "~/bin/pleroma stop"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
